<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>About | SharkSec</title>
    <link rel="stylesheet" href="styles/styles.css">
    <link href="https://fonts.googleapis.com/css2?family=Special+Gothic&family=Special+Gothic+Expanded+One&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Special+Gothic&display=swap" rel="stylesheet">
</head>
<body>

  
    <?php include 'nav.inc'; ?>
  

    <header class="header_jobs_page"> 
        <h1>About Us</h1> <!--Style h1, give it its own font using shorthand font property--> 
    </header>
    <!--USE SAME CLASS FOR THESE LISTS OR NAH? Maybe make list styles universal without class?-->
    <!--Nested list is generated by Gen AI. Prompt: "Can you please fix this nested loop:" (Input semi complete nested loop)-->
    <!--Change classes that are used in multiple pages to a more uniform name-->

    <div class="jobs_sections_grouped">
        <section class="jobs_page_section_1">
            <ul>
                <li><h3>Group Information</h3> <!--Simple way to make list heading font (defacto a heading)-->
                    <ul class="jobs_page_list"> <!--Reusing this class for simplicity-->
                        <li>Group Name: Sharks </li>
                        <li>16:30 - 18:30 Wednesday Class</li>
                        <li>Tutor: Rahul...</li>
                    </ul>
                </li>
                <li><h3>Student IDs</h3>
                    <ul class="jobs_page_list">
                        <li>105928204 - Jacob Liemareff</li>
                        <li>104177649 - Dulaj Dinujaya</li>
                        <li>106034458 - Alexander Kelly</li>
                    </ul>
                </li>
            </ul>    
        </section>   

        <!--Partially generated by Gen AI (to fix error where I put h3 tags in HTML)
         Prompt: "I need to somehow change the h3 tag to h3 in the css, because the HTML validator told me this is obsolete and that I should use css. 
         Here is my HTML:"(This is why I added the p element with the new class) (HTML was the one with the error that I have to ChatGPT-->
        <section class="jobs_page_section_2"> 
            <dl class="jobs_page_list">
                <dt><p class="about_name">Jacob Liemareff</p></dt> <!--If can't fix revert to using h3-->
                <dd>Completed jobs.html page, particpated in Jira management</dd>
        
                <dt><p class="about_name">Dulaj Dinujaya</p></dt>
                <dd>Completed apply.html page</dd>
        
                <dt><p class="about_name">Alex Kelly</p></dt>
                <dd>Created index.html page, logo (using genAI) and navigation bar, Jira</dd>
            </dl>
        </section>
    </div>

    <!--Used Gen AI to modify table to includea caption and merged cell 
    Prompt:Output a HTML table (Must have cell or row merged with a caption) for members's interests.
     There are 3 members in our group. put filler text in place of names and interests. !-->
    <table id="about_table">
        <caption id="about_table_caption"><h3>Group Members' Interests</h3></caption>
        <tr>
          <th>Name</th>
          <th colspan="2">Interests</th>
        </tr>
        <tr>
          <td>Jacob Liemareff</td>
          <td>Hiking and exploring the outdoors</td>
          <td>Eastern European history</td>
        </tr>
        <tr>
          <td>Dulaj</td>
          <td>Playing guitar</td>
          <td>Gaming</td>
        </tr>
        <tr>
          <td>Alex Kelly</td>
          <td>Music</td>
          <td>3D</td>
        </tr>
      </table>

      <!--The below images related code is primariliy Gen AI. 
      Prompt: How would I make three images go in the middle of a webpage, 
      horizontally aligned, but centered in he middle and add heading to each of the images-->
      <!--Then prompted again: "they are still stacked vertically"-->
      <div id="about_image-container">
        <div class="about_image-item">
            <h3>Jacob Liemareff</h3>
            <img src="images/Jacob.jpg" alt="Image of Alex Jacob Liemareff">
        </div>
        <div class="about_image-item">
            <h3>Dulaj Dinujaya</h3>
            <img src="images/dulaj_dinujaya.jpg" alt="Image of Dulaj">
        </div>
        <div class="about_image-item">
            <h3>Alex Kelly</h3>
            <img src="images/alex.jpg" alt="Image of Alex Kelly">
        </div>
    </div>


    <?php include 'footer.inc'; ?>
</html>
