
  <nav>
    <div id="nav-container">
      <div id="logo">
        <a href="index.php"><img src="images/logo.png" alt="SharkSec Logo"></a>
      </div>

      <ul >
        <li class="navbutton"><a href="index.php">Home</a></li>
        <li class="navbutton"><a href="jobs.php">Job listings</a></li>
        <li class="navbutton"><a href="apply.php">Apply for a job</a></li>
        <li class="navbutton"><a href="about.php">About us</a></li>
        <li class="navbutton"><a href="login.php">Manager log in</a></li>
        
      </ul>

      <div id="emailus"><a href="mailto:sharksecurity@example.com"> Email us</a></div>

    </div>
  </nav>